version: 2.1

jobs:
  b_config_job:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - run: echo "I'm from config b"

workflows:
  b_config_workflow:
    jobs:
      - b_config_job