version: 2.1

jobs:
  config_processor:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - checkout
      - run:
          name: Process Template Configs
          command: bash processor.sh

workflows:
  config_processor_workflow:
    jobs:
      - config_processor